- Directory.Packages.props
- UndercutF1.Console/UndercutF1.Console.csproj
By depending on the SkiaSharp.NativeAssets packages, we can ensure that the Skia native libraries are properly packaged in to the executable.
> Add Skia native assets to build output

- UndercutF1.Console/CommandHandler.cs
- UndercutF1.Console/ConsoleLoop.cs
* Fix the weird issue with line endings that caused only a single line to display on Windows.
* Change the way we read in input from the terminal by first checking if input is available using the classic System.Console API, instead of relying on read cancellation on `Terminal.ReadAsync`. This is because cancelling the read causes a byte to drop on Windows (see https://github.com/vezel-dev/cathode/issues/165)
> Fix Windows related issued

- UndercutF1.Data/Client/JsonTimingClient.cs
- UndercutF1.Data/Client/TimingService.cs
* When there are no events to receive, wait for half a second before checking again. This throttling should avoid the busy wait and prevent excessive CPU usage. Fixes #9.
* When calculating the session replay delay, make sure UTC is accounted for correctly.
> Improve session message handling

- UndercutF1.Console/Display/DriverTrackerDisplay.cs
- UndercutF1.Console/Display/TimingHistoryDisplay.cs
When both protocols are available, use Kitty instead of iTerm. Should fix #8.
Validated graphics do display in Kitty, Ghostty, and iTerm on Mac.
> Prefer to use the Kitty graphics protocol over iTerm

- .github/workflows/package.yml
- README.md
- UndercutF1.Console/UndercutF1.Console.csproj
- UndercutF1.Data/Client/JsonTimingClient.cs
Docker images are now pushed to DockerHub under the `justaman62/undercutf1` repository. Images are pushed with the `latest` tag, and a specific version tag.
> Publish a docker image as an alternative way to run the app

- README.md
- UndercutF1.Console/ConsoleLoop.cs
- UndercutF1.Console/Display/MainDisplay.cs
- UndercutF1.Console/Input/DelayInputHandler.cs
^M keypress conflicts with the enter keycode. Single second delay changes is now does by comma and period instead.
> Remove input handling for ^N and ^M 

- Directory.Packages.props
- Dockerfile
- README.md
- UndercutF1.Console/CommandHandler.Root.cs
- UndercutF1.Console/Display/DownloadTranscriptionModelDisplay.cs
- UndercutF1.Console/Display/TeamRadioDisplay.cs
- UndercutF1.Console/Input/DelayInputHandler.cs
- UndercutF1.Console/Input/DownloadTranscriptionModelInputHandler.cs
- UndercutF1.Console/Input/EscapeInputHandler.cs
- UndercutF1.Console/Input/TranscribeTeamRadioInputHandler.cs
- UndercutF1.Console/Screen.cs
- UndercutF1.Data/Interfaces/ITranscriptionProvider.cs
- UndercutF1.Data/TranscriptionProvider.cs
- UndercutF1.Data/UndercutF1.Data.csproj
- Have a confirmation page when you try to transcribe but don't have the Whisper model downloaded. This should help to ensure nobody is surprised when a 150mb file is downloaded.
- Upgrade Whisper.net and use package that supports all possible runtimes. This should mean that when available the GPU will be used for inference during transcription.
- Display the file location of downloaded team radio files
- Update docker image to include ffmpeg to ensure transcription works correctly.
Relates to #25
> Transcription improvements

- Directory.Packages.props
- UndercutF1.Console/UndercutF1.Console.csproj
- UndercutF1.Data/UndercutF1.Data.csproj
* Referencing all the Whisper runtimes caused excessive executable bloat
* Compress the executable when publishing. This might lead to slightly slower startup times, but personally isn't very noticeable.
> Reduce executable size

- .dockerignore
- .github/workflows/package.yml
- Directory.Build.props
- Directory.Packages.props
- Dockerfile
- README.md
- UndercutF1.Console/CommandHandler.ImportSession.cs
- UndercutF1.Console/CommandHandler.ListMeetings.cs
- UndercutF1.Console/CommandHandler.Root.cs
- UndercutF1.Console/CommandHandler.cs
- UndercutF1.Console/ConsoleLoop.cs
- UndercutF1.Console/Display/InfoDisplay.cs
- UndercutF1.Console/Display/MainDisplay.cs
- UndercutF1.Console/Input/SwitchToInfoInputHandler.cs
- UndercutF1.Console/Program.cs
- UndercutF1.Console/Screen.cs
- UndercutF1.Console/UndercutF1.Console.csproj
- UndercutF1.Data/DataImporter.cs
- UndercutF1.Data/Options/LiveTimingOptions.cs
- UndercutF1.Data/Processors/SessionInfoProcessor.cs
- UndercutF1.Data/Processors/TeamRadioProcessor.cs
- UndercutF1.Data/ServiceCollectionExtensions.cs
- UndercutF1.Data/UndercutF1.Data.csproj
* Implement a Info screen which shows the current configuration being used, and where you can go to change it
* Implement a simple version check that checks if the latest GitHub tag is the same as the current version
* Adjust data, log, and config directories to match up to established XDG and Windows standards. See updated README for what directories these are.
Fixes #29 
Fixes #30
> Use standard data/log directories, expose configuration information in TUI

- UndercutF1.Console/Display/DriverTrackerDisplay.cs
- UndercutF1.Console/Display/TimingHistoryDisplay.cs
- UndercutF1.Console/TerminalGraphics.cs
Chunk escape sequences sent to Kitty for the Kitty graphics protocol to 4000 byte chunks, as described in the spec. Chosen 4000 over the recommended 4096 to have a bit of a margin.
The images output are usually around 10KB (i.e. 10000 base64 chars), so we normally send 3 message for each image.
Fixes #8
> Chunk kitty graphics sequences to 4000 bytes

- UndercutF1.Console/Display/DriverTrackerDisplay.cs
- UndercutF1.Console/TerminalGraphics.cs
* After some experimentation, it seems that actually outputting a larger image reduces flickering (i.e., outputting a tiny image flickers a lot). maybe this means that the scaling of images to high resolution screens causes flickering?
Relates to #44
> More tuning for driver tracker image

- .github/workflows/ci.yml
- README.md
- UndercutF1.Console/Display/DriverTrackerDisplay.cs
- UndercutF1.Console/Display/IDisplay.cs
- UndercutF1.Data/DateTimeProvider.cs
% `pipx run codespell --ignore-words-list=iterm --skip="*.json,*.txt"`
```
./README.md:97: overlayed ==> overlaid
./README.md:141: instal ==> install
./UndercutF1.Console/Display/DriverTrackerDisplay.cs:340: Tranforms ==> Transforms
./UndercutF1.Console/Display/IDisplay.cs:13: whats ==> what's
./UndercutF1.Data/DateTimeProvider.cs:22: calcualte ==> calculate
```
% `pipx run codespell --ignore-words-list=iterm --skip="*.json,*.txt" --write-changes`
```
FIXED: ./README.md
FIXED: ./UndercutF1.Console/Display/DriverTrackerDisplay.cs
FIXED: ./UndercutF1.Console/Display/IDisplay.cs
FIXED: ./UndercutF1.Data/DateTimeProvider.cs
```
* https://pipx.pypa.io
* https://pypi.org/project/codespell
> Fix typos discovered by codespell

- UndercutF1.Console/ConsoleLoop.cs
- UndercutF1.Console/Display/DriverTrackerDisplay.cs
- UndercutF1.Console/Display/InfoDisplay.cs
- UndercutF1.Console/TerminalInfoProvider.cs
Dynamically scales the track map to be as close as possible to the actual pixels available for the rendering. The reduction in need for the terminal to rescale the image appears to reduce flashing due to re-renders.
Relates to #44
> Dynamically scale track map

- Directory.Packages.props
- README.md
- UndercutF1.Console/Audio/AudioPlayer.cs
- UndercutF1.Console/CommandHandler.Root.cs
- UndercutF1.Console/CommandHandler.cs
- UndercutF1.Console/Input/PlayTeamRadioInputHandler.cs
- UndercutF1.Console/Program.cs
- UndercutF1.Console/UndercutF1.Console.csproj
- UndercutF1.Data/Options/LiveTimingOptions.cs
Relates to #25.
Use our own callouts to `afplay`/`mpg123`/`ffplay` to playback team radio, instead of relying on `NetCoreAudio`. This way we can prevent terminal corruption, and have more control over error and playback states.
Adds new configuration to allow users to prefer the use of `ffplay` instead of `afplay`/`mpg123` on Mac/Linux. This should help give control to those who face any issues. `ffplay` is always used on Windows.
> Use custom audio playback implementation

- UndercutF1.Console/Display/TimingTowerDisplay.cs
- UndercutF1.Data/AutoMapper/TimingDataPointConfiguration.cs
- UndercutF1.Data/Client/TimingService.cs
- UndercutF1.Data/Models/TimingDataPoints/TimingDataPoint.cs
During non-race sessions, display the mini sector status (yellow, green, purple) on the sector time until the second has completed.
> Show mini sectors during qualifying

- README.md
- UndercutF1.Console/Api/ControlEndpoints.cs
- UndercutF1.Console/Api/TimingEndpoints.cs
- UndercutF1.Console/CommandHandler.Root.cs
Relates to #62, adds a new control API `POST http://localhost:61937/control` which allows you to pause or resume the session clock. This allows for manual integrations with third-party systems to control the currently running timing screen.
This is the initial implementation for #62, next up will be an option for more direct integrations with third-party services like Kodi, so you don't have to build your own.
> Implement a basic clock control API

- UndercutF1.Console/Display/TimingHistoryDisplay.cs
- UndercutF1.Data/Models/TimingDataPoints/TimingDataPoint.cs
- UndercutF1.Data/Processors/TimingDataProcessor.cs
* Track laps where the driver either exited or entered pits much more accurately
* This new property allows us to remove in/out laps from our history charts in a much cleaner way
> Track pit in/out laps more accurately in lap history to improve charts

- UndercutF1.Console/CommandHandler.Root.cs
- UndercutF1.Console/CommandHandler.cs
`info` command stopped working since the External Play Sync changes (embarrassing), so fixing the dependencies to make it work again.
> Fix info command

- UndercutF1.Console/ConsoleLoop.cs
- UndercutF1.Console/Display/DriverTrackerDisplay.cs
- UndercutF1.Console/Display/IDisplay.cs
- UndercutF1.Console/Display/TimingHistoryDisplay.cs
- UndercutF1.Console/Input/EscapeInputHandler.cs
In a bid to reduce graphics flashing and improve efficiency, we now only send the graphics sequences to the terminal if it has changed since the last draw. We currently need to still end it if the background screen as been redrawn, because that causes the old graphic to be removed.
Relates to #71
> Only update terminal graphics if they've changed since the last draw

- UndercutF1.Console/Program.cs
Relates to #93 (not yet a complete fix, need webview_csharp to also be fixed)
For the WebView to be allowed to spawn, the thread state _must_ be STA otherwise it will fail (silently...)
Docs:
https://github.com/webview/webview_csharp/blob/3233b1235fbc0365ff03296703d947da5e64d5e8/README.md?plain=1#L34-L42
> Fix incorrect thread state for WebView on Windows

- UndercutF1.Console/Display/DriverTrackerDisplay.cs
- UndercutF1.Console/Display/InfoDisplay.cs
- UndercutF1.Console/Display/TimingHistoryDisplay.cs
- UndercutF1.Console/Graphics/SKImageExtensions.cs
For some reason the recent iTerm2 release makes the app think it supports Kitty graphics, but displaying Kitty graphics causes issues in the terminal and no image is actually visible. Need to determine why this is happening, but for now it makes sense to prefer the simpler iTerm2 protocol when supported anyway.
> Prefer iTerm graphics protocol when enabled

- UndercutF1.Console/CommandHandler.Login.cs
- UndercutF1.Console/ConsoleLoop.cs
- UndercutF1.Console/Display/DriverTrackerDisplay.cs
- UndercutF1.Console/Display/InfoDisplay.cs
- UndercutF1.Console/Display/MainDisplay.cs
- UndercutF1.Console/Display/SessionStatsDisplay.cs
- UndercutF1.Console/Graphics/TerminalGraphics.cs
- UndercutF1.Console/TerminalInfoProvider.cs
- UndercutF1.Data/Client/LiveTimingClient.cs
- UndercutF1.Data/Formula1Account.cs
* Ensure all Kitty chunks are sent with the quiet flag. iTerm2 will otherwise send back a ack response for every chunk (don't think other terminals do this)
* Cleanup terminal info queries to make sure we aren't logging junk memory
* Reduce complexity of the F1 account token logic to prevent duplicate processing
> Cleanup Terminal Graphics queries
